/**
 * Gallery media library.
 *
 * The files themselves are generated by `node scripts/build-media.mjs` from the originals in
 * media-src/ (gitignored). That script owns the category -> source-photo mapping; the counts
 * below must match the per-category totals it prints. To add photos: drop them in media-src,
 * add them to CATEGORIES in the script, re-run it, and bump the count here.
 */

export type GalleryCategory = 'transport' | 'equipment' | 'camps' | 'catering' | 'projects';

export const GALLERY_CATEGORIES: GalleryCategory[] = [
  'transport',
  'equipment',
  'camps',
  'catering',
  'projects',
];

/** How many photos build-media.mjs emitted per category. */
const PHOTO_COUNTS: Record<GalleryCategory, number> = {
  transport: 26,
  equipment: 11,
  camps: 20,
  catering: 12,
  projects: 9,
};

interface GalleryItemBase {
  /** 600x600 WebP for the aspect-square grid tile. */
  thumb: string;
  category: GalleryCategory;
}

export interface GalleryPhoto extends GalleryItemBase {
  kind: 'photo';
  /** Long edge <= 1600 WebP, fetched only when the lightbox opens. */
  full: string;
}

export interface GalleryVideo extends GalleryItemBase {
  kind: 'video';
  src: string;
  poster: string;
  width: number;
  height: number;
}

export type GalleryItem = GalleryPhoto | GalleryVideo;

const photos = (category: GalleryCategory): GalleryPhoto[] =>
  Array.from({ length: PHOTO_COUNTS[category] }, (_, i) => {
    const name = `${category}-${String(i + 1).padStart(2, '0')}`;
    return {
      kind: 'photo',
      category,
      thumb: `/assets/gallery/${category}/${name}-thumb.webp`,
      full: `/assets/gallery/${category}/${name}.webp`,
    };
  });

const videos: GalleryVideo[] = [
  {
    kind: 'video',
    category: 'transport',
    src: '/assets/video/rig-move.mp4',
    poster: '/assets/video/rig-move-poster.webp',
    thumb: '/assets/video/rig-move-thumb.webp',
    // Portrait phone footage: the file is stored 1024x576 with a -90 rotation matrix, so these
    // are the dimensions the browser actually displays.
    width: 576,
    height: 1024,
  },
];

/**
 * Round-robin across categories so the unfiltered "All" view opens on a mix of trucks, camps
 * and catering rather than 26 consecutive fleet shots. Filtering preserves this relative order.
 */
function interleave(groups: GalleryItem[][]): GalleryItem[] {
  const out: GalleryItem[] = [];
  const longest = Math.max(...groups.map((g) => g.length));
  for (let i = 0; i < longest; i++) {
    for (const group of groups) {
      if (group[i]) out.push(group[i]);
    }
  }
  return out;
}

export const galleryItems: GalleryItem[] = interleave(
  GALLERY_CATEGORIES.map((category) => {
    const group: GalleryItem[] = photos(category);
    // Videos lead their category so the play badge is visible without paging.
    return [...videos.filter((v) => v.category === category), ...group];
  }),
);
