/**
 * The photo library: one row per image, and the only place a photo's meaning is recorded.
 *
 * The files themselves are generated by `node scripts/build-media.mjs` from the originals
 * in media-src/ (gitignored). That script owns which source photo becomes which numbered
 * derivative; this file owns what each derivative is *of*.
 *
 * `dir` (taken from the id prefix) is only where the bytes live and never changes.
 * `company` and `category` say where a photo is shown and default to the folder's owner.
 * `tags` say what it depicts, and that is what lets a page ask for exactly the ARGAS photos
 * or exactly the Jaber crossing photos instead of dumping a whole category.
 *
 * To retag: edit a row. To add photos: add them in build-media.mjs, re-run it, append rows.
 */
import type { CompanyId } from './companies';

export type GalleryCategory = 'transport' | 'equipment' | 'camps' | 'catering' | 'projects';

export const GALLERY_CATEGORIES: GalleryCategory[] = [
  'transport',
  'equipment',
  'camps',
  'catering',
  'projects',
];

/** Physical folders under /assets/gallery/. Happen to share the category names today. */
type MediaDir = GalleryCategory;

/**
 * Closed vocabulary, so a typo is a compile error rather than a photo that silently
 * never appears in any strip.
 */
export type MediaTag =
  // Projects
  | 'argas' | 'adnoc' | 'al-jaffr' | 'azraq' | 'sarhan'
  // Border crossings
  | 'jaber' | 'tarbil' | 'al-karamah' | 'al-omari'
  // Subjects
  | 'fleet' | 'flatbed' | 'lowbed' | 'tanker' | 'forklift' | 'crane' | 'winch' | 'loader'
  | 'caravan' | 'kitchen' | 'dining' | 'accommodation' | 'office' | 'workshop' | 'crew'
  | 'night-ops' | 'convoy' | 'loading'
  // Camp welfare and housekeeping
  | 'laundry' | 'ablutions' | 'recreation' | 'hygiene'
  // Context
  | 'border' | 'desert' | 'site' | 'warehouse' | 'amman';

/** Which company a folder's photos belong to unless a row says otherwise. */
const DIR_OWNER: Record<MediaDir, CompanyId> = {
  transport: 'transport',
  equipment: 'project-services',
  camps: 'project-services',
  catering: 'project-services',
  projects: 'project-services',
};

/** A hand-edited row. Everything except `id` is optional and falls back to the folder. */
interface MediaSeed {
  id: string;
  company?: CompanyId;
  category?: GalleryCategory;
  tags?: MediaTag[];
  alt?: { en: string; ar: string };
  /** Good enough to carry a hero or a FeatureSplit, not just a grid tile. */
  featured?: boolean;
}

interface MediaBase {
  id: string;
  dir: MediaDir;
  company: CompanyId;
  category: GalleryCategory;
  tags: MediaTag[];
  alt?: { en: string; ar: string };
  featured: boolean;
  /** 600x600 WebP for the aspect-square grid tile. */
  thumb: string;
}

export interface MediaPhoto extends MediaBase {
  kind: 'photo';
  /** Long edge <= 1600 WebP, fetched only when the lightbox opens. */
  full: string;
}

export interface MediaVideo extends MediaBase {
  kind: 'video';
  src: string;
  poster: string;
  width: number;
  height: number;
}

/** Discriminated on `kind`. Narrow with it before reaching for video-only fields. */
export type MediaItem = MediaPhoto | MediaVideo;

/**
 * Seeded from the folder layout with empty tags. Phase 10 of the renovation is a pass
 * over all 78 thumbnails to fill in tags, alt text and featured flags, and to move the
 * border-handling photos to `company: 'logistics'`.
 */
const SEED: MediaSeed[] = [
  // ── transport/: fleet, cross-border haulage ───────────────────────────────
  // Baseline `fleet` tag: true of the whole folder by construction. Per-photo subjects
  // (flatbed vs tanker vs convoy) and alt text still want a human pass. See the
  // equipment and catering blocks below for the level of detail to aim for.
  { id: 'transport-01', tags: ['fleet'], featured: true },
  { id: 'transport-02', tags: ['fleet'] },
  { id: 'transport-03', tags: ['fleet'] },
  { id: 'transport-04', tags: ['fleet'] },
  { id: 'transport-05', tags: ['fleet'] },
  { id: 'transport-06', tags: ['fleet'] },
  { id: 'transport-07', tags: ['fleet'], featured: true },
  { id: 'transport-08', tags: ['fleet'] },
  { id: 'transport-09', tags: ['fleet'] },
  { id: 'transport-10', tags: ['fleet'] },
  { id: 'transport-11', tags: ['fleet'] },
  { id: 'transport-12', tags: ['fleet'] },
  { id: 'transport-13', tags: ['fleet', 'convoy'], featured: true },
  { id: 'transport-14', tags: ['fleet'] },
  { id: 'transport-15', tags: ['fleet'] },
  { id: 'transport-16', tags: ['fleet'] },
  { id: 'transport-17', tags: ['fleet'] },
  { id: 'transport-18', tags: ['fleet'] },
  { id: 'transport-19', tags: ['fleet', 'loading'], featured: true },
  { id: 'transport-20', tags: ['fleet'] },
  { id: 'transport-21', tags: ['fleet'] },
  { id: 'transport-22', tags: ['fleet'] },
  { id: 'transport-23', tags: ['fleet'] },
  { id: 'transport-24', tags: ['fleet'] },
  { id: 'transport-25', tags: ['fleet'] },
  { id: 'transport-26', tags: ['fleet'] },

  // ── equipment/: heavy machinery, forklifts, lifting gear ──────────────────
  // The forklift and border-yard shots are the logistics company's kit, not the project
  // company's, so they carry `company: 'logistics'` while staying in the equipment folder.
  {
    id: 'equipment-01',
    tags: ['site'],
    alt: {
      en: 'Containerised CAT generator set for site power',
      ar: 'مولّد كاتربيلر داخل حاوية لتغذية الموقع بالكهرباء',
    },
  },
  {
    id: 'equipment-02',
    company: 'logistics',
    tags: ['crane', 'border', 'loading'],
    featured: true,
    alt: {
      en: 'Gantry crane lifting over a loaded trailer at a border yard',
      ar: 'رافعة جسرية تعمل فوق مقطورة محمّلة في ساحة حدودية',
    },
  },
  {
    id: 'equipment-03',
    company: 'logistics',
    tags: ['forklift', 'warehouse'],
    alt: {
      en: 'Forklift fleet under maintenance in the workshop',
      ar: 'أسطول الرافعات الشوكية أثناء الصيانة في الورشة',
    },
  },
  {
    id: 'equipment-04',
    company: 'logistics',
    tags: ['crane'],
    alt: {
      en: 'Grove mobile crane boomed up in the equipment yard',
      ar: 'رافعة جروف المتنقلة بذراع ممدود في ساحة المعدات',
    },
  },
  {
    id: 'equipment-05',
    tags: ['site'],
    featured: true,
    alt: {
      en: 'Enclosed diesel generator set serving a project camp',
      ar: 'مولّد ديزل داخل حاوية عازلة يخدم مخيم المشروع',
    },
  },
  {
    id: 'equipment-06',
    company: 'logistics',
    tags: ['forklift'],
    featured: true,
    alt: {
      en: 'Row of forklifts in multiple capacities ready for dispatch',
      ar: 'صف من الرافعات الشوكية بطاقات متعددة جاهزة للإرسال',
    },
  },
  {
    id: 'equipment-07',
    tags: ['desert', 'site'],
    alt: {
      en: 'Bulldozer and excavator preparing a desert site',
      ar: 'جرافة وحفّارة أثناء تهيئة موقع صحراوي',
    },
  },
  {
    id: 'equipment-08',
    company: 'logistics',
    tags: ['forklift'],
    alt: {
      en: 'Newly delivered Komatsu forklifts awaiting commissioning',
      ar: 'رافعات كوماتسو شوكية حديثة الوصول بانتظار التشغيل',
    },
  },
  {
    id: 'equipment-09',
    tags: ['site'],
    alt: {
      en: 'Telehandler and boom lift working alongside project trucks',
      ar: 'رافعة تلسكوبية ومنصة عمل مرتفعة بجانب شاحنات المشروع',
    },
  },
  {
    id: 'equipment-10',
    tags: ['crane', 'site', 'desert'],
    featured: true,
    alt: {
      en: 'Mobile cranes setting fresh-water tanks at a desert camp',
      ar: 'رافعات متنقلة تُنزل خزانات مياه عذبة في مخيم صحراوي',
    },
  },
  {
    id: 'equipment-11',
    tags: ['crane', 'desert', 'site', 'loading'],
    alt: {
      en: 'Crane loading site equipment onto a flatbed in the desert',
      ar: 'رافعة تُحمّل معدات الموقع على مقطورة مسطّحة في الصحراء',
    },
  },

  // ── camps/: accommodation, caravans, site infrastructure ──────────────────
  // Baseline `accommodation` + `caravan` tags: true of the folder by construction.
  { id: 'camps-01', tags: ['accommodation', 'caravan'], featured: true },
  { id: 'camps-02', tags: ['accommodation', 'caravan'] },
  { id: 'camps-03', tags: ['accommodation', 'caravan'] },
  { id: 'camps-04', tags: ['accommodation', 'caravan'] },
  { id: 'camps-05', tags: ['accommodation', 'caravan'] },
  { id: 'camps-06', tags: ['accommodation', 'caravan'] },
  { id: 'camps-07', tags: ['accommodation', 'caravan'], featured: true },
  { id: 'camps-08', tags: ['accommodation', 'caravan'] },
  { id: 'camps-09', tags: ['accommodation', 'caravan'] },
  { id: 'camps-10', tags: ['accommodation', 'caravan'] },
  { id: 'camps-11', tags: ['accommodation', 'caravan'] },
  { id: 'camps-12', tags: ['accommodation', 'caravan'] },
  { id: 'camps-13', tags: ['accommodation', 'caravan'], featured: true },
  { id: 'camps-14', tags: ['accommodation', 'caravan'] },
  { id: 'camps-15', tags: ['accommodation', 'caravan'] },
  { id: 'camps-16', tags: ['accommodation', 'caravan'] },
  { id: 'camps-17', tags: ['accommodation', 'caravan'] },
  { id: 'camps-18', tags: ['accommodation', 'caravan'] },
  { id: 'camps-19', tags: ['accommodation', 'caravan'] },
  { id: 'camps-20', tags: ['accommodation', 'caravan'] },

  // Added from the 2026 ARGAS and ADNOC handover sets. The folder each arrived in
  // named the project, so unlike the original seed these carry a real project tag.
  { id: 'camps-21', tags: ['adnoc', 'site'] },
  { id: 'camps-22', tags: ['adnoc', 'site'] },
  { id: 'camps-23', tags: ['adnoc', 'recreation'] },
  { id: 'camps-24', tags: ['adnoc', 'accommodation'] },
  { id: 'camps-25', tags: ['adnoc', 'site'] },
  { id: 'camps-26', tags: ['adnoc', 'accommodation'] },
  { id: 'camps-27', tags: ['adnoc', 'site'] },
  { id: 'camps-28', tags: ['adnoc', 'recreation'] },
  { id: 'camps-29', tags: ['adnoc', 'recreation'] },
  { id: 'camps-30', tags: ['adnoc', 'site'] },
  { id: 'camps-31', tags: ['argas', 'al-jaffr', 'accommodation'] },
  { id: 'camps-32', tags: ['argas', 'al-jaffr', 'accommodation'] },
  { id: 'camps-33', tags: ['argas', 'al-jaffr', 'accommodation'] },
  { id: 'camps-34', tags: ['argas', 'al-jaffr', 'ablutions'] },
  { id: 'camps-35', tags: ['argas', 'al-jaffr', 'laundry'] },
  { id: 'camps-36', tags: ['argas', 'al-jaffr', 'laundry'] },
  { id: 'camps-37', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-38', tags: ['argas', 'al-jaffr', 'accommodation'] },
  { id: 'camps-39', tags: ['argas', 'al-jaffr', 'crew'] },
  { id: 'camps-40', tags: ['argas', 'al-jaffr', 'laundry'] },
  { id: 'camps-41', tags: ['argas', 'al-jaffr', 'ablutions'] },
  { id: 'camps-42', tags: ['argas', 'al-jaffr', 'ablutions'] },
  { id: 'camps-43', tags: ['argas', 'al-jaffr', 'ablutions'] },
  { id: 'camps-44', tags: ['argas', 'al-jaffr', 'crew'] },
  { id: 'camps-45', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-46', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-47', tags: ['argas', 'al-jaffr', 'crew'] },
  { id: 'camps-48', tags: ['argas', 'al-jaffr', 'laundry'] },
  { id: 'camps-49', tags: ['argas', 'al-jaffr', 'accommodation'] },
  { id: 'camps-50', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-51', tags: ['argas', 'al-jaffr', 'hygiene'] },
  { id: 'camps-52', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-53', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-54', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-55', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-56', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-57', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-58', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-59', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-60', tags: ['argas', 'al-jaffr', 'site'] },
  { id: 'camps-61', tags: ['argas', 'al-jaffr', 'recreation'] },

  // ── catering/: kitchens, dining, welfare and housekeeping ─────────────────
  // Despite the folder name this set is mostly camp life: two food shots, the rest are
  // laundry, ablutions, pest control and the crew areas that keep people on site.
  {
    id: 'catering-01',
    tags: ['recreation', 'crew'],
    featured: true,
    alt: {
      en: 'Air-conditioned crew lounge with seating and a television',
      ar: 'صالة استراحة مكيّفة للطاقم بمقاعد وشاشة تلفزيون',
    },
  },
  {
    id: 'catering-02',
    tags: ['laundry'],
    alt: {
      en: 'Camp laundry room lined with washing machines',
      ar: 'غرفة غسيل المخيم مصطفّة بالغسالات',
    },
  },
  {
    id: 'catering-03',
    tags: ['hygiene'],
    alt: {
      en: 'Technician in protective gear treating a camp unit',
      ar: 'فنّي بمعدات وقاية أثناء معالجة إحدى وحدات المخيم',
    },
  },
  {
    id: 'catering-04',
    tags: ['recreation', 'caravan', 'desert'],
    alt: {
      en: 'Camp grounds at dusk with seating and the Jordanian flag',
      ar: 'ساحات المخيم عند الغروب بمقاعد والعلم الأردني',
    },
  },
  {
    id: 'catering-05',
    tags: ['recreation', 'crew'],
    featured: true,
    alt: {
      en: 'Shaded outdoor seating area beside the accommodation units',
      ar: 'منطقة جلوس خارجية مظلّلة بجانب وحدات الإقامة',
    },
  },
  {
    id: 'catering-06',
    tags: ['recreation', 'crew', 'night-ops'],
    alt: {
      en: 'Crew gathered in the outdoor lounge for an evening screening',
      ar: 'الطاقم مجتمع في الاستراحة الخارجية لعرض مسائي',
    },
  },
  {
    id: 'catering-07',
    tags: ['kitchen', 'caravan'],
    featured: true,
    alt: {
      en: 'Camp kitchen unit with its serving hatch',
      ar: 'وحدة مطبخ المخيم مع نافذة التقديم',
    },
  },
  {
    id: 'catering-08',
    tags: ['dining', 'kitchen'],
    featured: true,
    alt: {
      en: 'Camp dining hall and a plated meal ready for the shift',
      ar: 'صالة طعام المخيم ووجبة جاهزة لوردية العمل',
    },
  },
  {
    id: 'catering-09',
    tags: ['hygiene', 'site'],
    alt: {
      en: 'Hygiene treatment being carried out at a rig site',
      ar: 'أعمال التعقيم أثناء تنفيذها في موقع الحفر',
    },
  },
  {
    id: 'catering-10',
    tags: ['ablutions'],
    alt: {
      en: 'Ablution block with washbasins and shower cubicles',
      ar: 'وحدة اغتسال بمغاسل وكبائن استحمام',
    },
  },
  {
    id: 'catering-11',
    tags: ['recreation'],
    alt: {
      en: 'Landscaped shaded terrace between the accommodation blocks',
      ar: 'شرفة مظلّلة منسّقة بين مجمّعات الإقامة',
    },
  },
  {
    id: 'catering-12',
    tags: ['laundry'],
    alt: {
      en: 'Industrial washing machines in the camp laundry',
      ar: 'غسالات صناعية في مغسلة المخيم',
    },
  },

  // Added from the 2026 ARGAS and ADNOC handover sets. Same provenance as the camps
  // block above: the source folder named the project, so the tags are not guesses.
  { id: 'catering-13', tags: ['adnoc', 'kitchen'] },
  { id: 'catering-14', tags: ['adnoc', 'kitchen'] },
  { id: 'catering-15', tags: ['adnoc', 'dining'] },
  { id: 'catering-16', tags: ['adnoc', 'warehouse'] },
  { id: 'catering-17', tags: ['adnoc', 'warehouse'] },
  { id: 'catering-18', tags: ['adnoc', 'kitchen', 'crew'] },
  { id: 'catering-19', tags: ['adnoc', 'dining'] },
  { id: 'catering-20', tags: ['adnoc', 'dining'] },
  { id: 'catering-21', tags: ['adnoc', 'dining'] },
  { id: 'catering-22', tags: ['adnoc', 'kitchen'] },
  { id: 'catering-23', tags: ['adnoc', 'dining'] },
  { id: 'catering-24', tags: ['adnoc', 'dining'] },
  { id: 'catering-25', tags: ['adnoc', 'warehouse'] },
  { id: 'catering-26', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-27', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-28', tags: ['argas', 'al-jaffr', 'warehouse'] },
  { id: 'catering-29', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-30', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-31', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-32', tags: ['argas', 'al-jaffr', 'warehouse'] },
  { id: 'catering-33', tags: ['argas', 'al-jaffr', 'warehouse'] },
  { id: 'catering-34', tags: ['argas', 'al-jaffr', 'warehouse'] },
  { id: 'catering-35', tags: ['argas', 'al-jaffr', 'warehouse'] },
  { id: 'catering-36', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-37', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-38', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-39', tags: ['argas', 'al-jaffr', 'kitchen', 'crew'] },
  { id: 'catering-40', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-41', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-42', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-43', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-44', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-45', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-46', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-47', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-48', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-49', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-50', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-51', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-52', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-53', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-54', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-55', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-56', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-57', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-58', tags: ['argas', 'al-jaffr', 'kitchen'] },
  { id: 'catering-59', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-60', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-61', tags: ['argas', 'al-jaffr', 'dining'] },
  { id: 'catering-62', tags: ['argas', 'al-jaffr', 'dining'] },

  // ── projects/: on-site operations ─────────────────────────────────────────
  // Baseline `site` tag only. Which of these are ARGAS at Al-Jaffr and which are ADNOC
  // at Azraq/Sarhan is not something the photos say. That attribution has to come from
  // someone who was there, and until it does the case studies fall back to the company's
  // whole set rather than claiming a photo belongs to a project it may not.
  { id: 'projects-01', tags: ['site'], featured: true },
  { id: 'projects-02', tags: ['site'] },
  { id: 'projects-03', tags: ['site'] },
  { id: 'projects-04', tags: ['site'] },
  { id: 'projects-05', tags: ['site'], featured: true },
  { id: 'projects-06', tags: ['site'] },
  { id: 'projects-07', tags: ['site'] },
  { id: 'projects-08', tags: ['site'] },
  { id: 'projects-09', tags: ['site'] },
];

const dirOf = (id: string) => id.replace(/-\d+$/, '') as MediaDir;

const photos: MediaPhoto[] = SEED.map((seed) => {
  const dir = dirOf(seed.id);
  return {
    id: seed.id,
    dir,
    company: seed.company ?? DIR_OWNER[dir],
    category: seed.category ?? dir,
    tags: seed.tags ?? [],
    alt: seed.alt,
    featured: seed.featured ?? false,
    kind: 'photo',
    thumb: `/assets/gallery/${dir}/${seed.id}-thumb.webp`,
    full: `/assets/gallery/${dir}/${seed.id}.webp`,
  };
});

const videos: MediaVideo[] = [
  {
    id: 'rig-move',
    dir: 'transport',
    company: 'transport',
    category: 'transport',
    tags: ['lowbed', 'convoy'],
    featured: false,
    kind: 'video',
    src: '/assets/video/rig-move.mp4',
    poster: '/assets/video/rig-move-poster.webp',
    thumb: '/assets/video/rig-move-thumb.webp',
    // Portrait phone footage: the file is stored 1024x576 with a -90 rotation matrix, so
    // these are the dimensions the browser actually displays.
    width: 576,
    height: 1024,
  },
];

export const media: MediaItem[] = [...videos, ...photos];

export interface MediaQuery {
  company?: CompanyId | 'all';
  category?: GalleryCategory | 'all';
  /** Photos carrying ALL of these tags (default) or ANY of them. */
  tags?: MediaTag[];
  match?: 'all' | 'any';
  featured?: boolean;
  limit?: number;
}

/** Below this a strip reads as broken rather than curated in a four-column grid. */
const MIN_STRIP = 4;

/**
 * The one query used by the gallery grid, every photo strip, every feature split and
 * every company hero.
 *
 * Tagged photos always come first. A thin or empty tag match is topped up from the
 * company's own set rather than left short, because the library is tagged incrementally, so a
 * page whose subject is not fully tagged yet should still look finished.
 */
export function mediaFor(q: MediaQuery = {}): MediaItem[] {
  const base = media.filter(
    (m) =>
      (!q.company || q.company === 'all' || m.company === q.company) &&
      (!q.category || q.category === 'all' || m.category === q.category) &&
      (q.featured === undefined || m.featured === q.featured),
  );

  let out = base;
  if (q.tags?.length) {
    const want = q.tags;
    const tagged = base.filter((m) =>
      q.match === 'any'
        ? want.some((t) => m.tags.includes(t))
        : want.every((t) => m.tags.includes(t)),
    );
    out =
      tagged.length >= MIN_STRIP
        ? tagged
        : [...tagged, ...base.filter((m) => !tagged.includes(m))];
  }

  return q.limit ? out.slice(0, q.limit) : out;
}

/** Categories that actually have photos for a company, which drives the gallery's second filter row. */
export const categoriesFor = (company: CompanyId | 'all'): GalleryCategory[] =>
  GALLERY_CATEGORIES.filter((c) =>
    media.some((m) => m.category === c && (company === 'all' || m.company === company)),
  );

/**
 * Structural guards. Module scope, so a bad edit fails `npm run build` rather than
 * showing up as an empty grid in production. File existence is checked separately by
 * scripts/check-media.mjs, which can touch the filesystem.
 */
const seen = new Set<string>();
for (const m of media) {
  if (seen.has(m.id)) throw new Error(`[media] duplicate id: ${m.id}`);
  seen.add(m.id);
}
for (const c of GALLERY_CATEGORIES) {
  if (!media.some((m) => m.category === c)) throw new Error(`[media] category has no photos: ${c}`);
}
